{% set name = "dm-env" %}
{% set version = "1.5" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 3efd99b0652563599507c415d48b51896c88be2f01c2b6250af8bab51571e353

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - absl-py
    - dm-tree
    - numpy
    - python >=3.6

test:
  imports:
    - dm_env
  commands:
    - pip check
    - nosetests dm_env
  requires:
    - pip
    - nose

about:
  home: https://pypi.org/project/dm-env
  summary: A Python interface for Reinforcement Learning environments.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/deepmind/dm_env
  doc_url: https://github.com/deepmind/dm_env/blob/{{ version }}/docs/index.md

extra:
  recipe-maintainers:
    - bollwyvl
